=== clarin-eric/VirtualCollectionRegistry/VirtualCollectionRegistry/src/main/resources/META-INF/VirtualCollection.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  elementFormDefault="unqualified">

  <xs:element name="VirtualCollections">
    <xs:complexType>
      <xs:sequence maxOccurs="unbounded">
        <xs:element ref="VirtualCollection"/>
      </xs:sequence>
      <xs:attribute name="totalCount" type="xs:integer"/>
      <xs:attribute name="offset" type="xs:integer"/>
      <xs:attribute name="result">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="full"/>
            <xs:enumeration value="partial"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="VirtualCollection">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Name" type="xs:string"/>
        <xs:element minOccurs="0" name="Description" type="xs:string"/>
        <xs:element minOccurs="0" name="CreationDate" type="xs:date"/>
        <xs:element name="Type">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="extensional"/>
              <xs:enumeration value="intensional"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element minOccurs="0" name="Creator">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Name" type="xs:string"/>
              <xs:element minOccurs="0" name="Email" type="xs:string"/>
              <xs:element minOccurs="0" name="Organisation" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="ref" type="xs:IDREF"/>
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="0" name="Purpose">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="research"/>
              <xs:enumeration value="reference"/>
              <xs:enumeration value="sample"/>
              <xs:enumeration value="future-use"/>
              <!-- to be extended -->
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element minOccurs="0" name="Reproducibility">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="intended"/>
              <xs:enumeration value="fluctuating"/>
              <xs:enumeration value="untended"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element minOccurs="0" name="ReproducibilityNotice" type="xs:string"/>
        <xs:element name="Resources">
          <xs:complexType>
            <xs:sequence maxOccurs="unbounded">
              <xs:element name="Resource">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="ResourceType">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:enumeration value="Metadata"/>
                          <xs:enumeration value="Resource"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="ResourceRef">
                      <xs:simpleType>
                        <xs:restriction base="xs:anyURI"/>
                      </xs:simpleType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="GeneratedBy" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Description" type="xs:string"/>
              <xs:element name="Query" minOccurs="0">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="profile" type="xs:string" use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="id" type="xs:long" use="optional" />
      <xs:attribute name="persistentId" type="xs:string"
        use="optional" />
      <xs:attribute name="state" use="optional">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="private" />
            <xs:enumeration value="public-pending" />
            <xs:enumeration value="public" />
            <xs:enumeration value="deleted" />
            <xs:enumeration value="dead" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== clarin-eric/VirtualCollectionRegistry/src/test/resources/VirtualCollection-extensional.xml
<?xml version="1.0" encoding="UTF-8"?>
<VirtualCollection xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="VirtualCollection.xsd">
    <Type>extensional</Type>
    <Name>Test Collection 1</Name>
    <Description>Test Description</Description>
    <CreationDate>2009-12-31</CreationDate>
    <Creators>
        <Creator>
            <Name>Joe User</Name>
            <Email>joe.user@example.com</Email>
            <Organisation>Example Organization</Organisation>
        </Creator>
        <Creator>
            <Name>Jane User</Name>
            <Email>jane.user@example.com</Email>
            <Organisation>Example Organization</Organisation>
        </Creator>
    </Creators>
    <Purpose>sample</Purpose>
    <Reproducibility>untended</Reproducibility>
    <ReproducibilityNotice>Unmaintaned test collection.</ReproducibilityNotice>
    <Keywords>
        <Keyword>test</Keyword>
        <Keyword>unmaintained</Keyword>
    </Keywords>
    <Resources>
        <Resource>
            <ResourceType>Metadata</ResourceType>
            <ResourceRef>http://hdl.handle.net/1839/00-0000-0000-0005-671C-C</ResourceRef>
        </Resource>
        <Resource>
            <ResourceType>Metadata</ResourceType>
            <ResourceRef>http://hdl.handle.net/1839/00-0000-0000-0006-671C-C</ResourceRef>
        </Resource>
        <Resource>
            <ResourceType>Metadata</ResourceType>
            <ResourceRef>http://hdl.handle.net/1839/00-0000-0000-0007-671C-C</ResourceRef>
        </Resource>
    </Resources>
</VirtualCollection>
